### ISSUE TITLE
Internationalization (i18n) and Localization (l10n) Support

### ISSUE THREAD

**Issue by gcotelli** [ba-st/Buoy#127]
# Background
**Internationalization**, often shortened to "i18n", is the practice of designing a system in such a way that it can easily be adapted for different target audiences, that may vary in region, language, or culture.
The complementary process of adapting a system for a specific target audience is called Localization. **Localization** (l10n) is the process of adapting a software user interface to a specific culture.

The following are common factors to consider:

- language
- unit of measure (e.g., kilometers in Europe, miles in U.S.)
- text direction (e.g., European languages are left-to-right, Arabic right-to-left)
- capitalization in Latin script (e.g., English uses capitals for weekdays, Spanish uses lowercase)
- adaptation of idioms (e.g., "raining cats and dogs" makes no sense when translated literally)
- use of register (e.g., in Japanese respectful speech differs exceptionally from casual speech)
- number format (e.g., 10 000,00 in Germany vs. 10,000.00 in the U.S.)
- date format
- currency
- cultural references
- paper size
- color psychology
- compliance with local laws
- local holidays
- personal names

# Scope
This feature intends to provide basic building blocks easing the localization of an application using Buoy as a dependency. The initial scope includes:
- [x] Basic support for translations (#126)
- [ ] Locale-aware number formatting
- [ ] Locale-aware chronology objects formatting (dates, times, etc)
- [x] Extraction of translation units from source code (#129 #130)
- [x] Loading translations on an image (#129 #130)

Other projects can complement this behavior once the building blocks are in place, like [Aconcagua](https://github.com/ba-st/Aconcagua) adding localization support for units of measure, [Chalten](https://github.com/ba-st/Chalten) adding localization support for its chronology abstractions, and so on.
